### ISSUE TITLE
Giving user option to input seconds or not

### ISSUE THREAD

**Issue by androdnoc** [NOC-MDP/issue-tracking--polpred_offshore#7]
In terms of handling seconds, seconds can be removed quite simply due to how HTML time input fields are handled, theres essentialy two types:

![image](https://user-images.githubusercontent.com/45202929/83640173-af72a580-a5a3-11ea-9eef-b3713a784a26.png)

Since the API currently uses seconds, a ``:00`` can be appended to the end of the user input when the values are sent to the API.

**Comment by NOC-ColinBell** [comment]
Although seconds would be rarely inputted I don't have a preference whether they appear or not.  They do in POLPRED (desktop) but that is because the standard time control has it in and I never bothered disabling it.  I'd probably leave seconds there if it is there right now as you don'y have to put anything in there - assume it defaults to ':00'

**Comment by androdnoc** [comment]
Have updated so that user only inputs hours and minutes. However, the UTC format will still need to be used whenb calling the Polpred API (``0000-00-00T00:00:00:00Z``)
